### ISSUE TITLE
Invalid filesystem data causes program abort

### ISSUE THREAD

**Issue by maxirmx** [tamatebako/libdwarfs#75]
On linux platform (with GCC and clang) invalid filesystem data causes program abort (exception generated in dwarfs library fails be handled outside)
Failing tests:

- tebako_load_invalid_filesystem
- tebako_load_invalid_offset

It is a minor  issue for Tebako packager since in a case of broken filesystem the execution has to be terminated on way or another

**Comment by maxirmx** [comment]
It is during execution.
It happens  if filesystem image is broken which should not happen if tebako is used.
If someone packages manually he can put there some broken file.   In this case exception is not handled and the package terminates with message "Aborted"  instead of "Invalid file system", "No filesysten found", ...
I do not think it is a real issue for tebako case

**Comment by ronaldtse** [comment]
> If someone packages manually he can put there some broken file. In this case exception is not handled and the package terminates with message "Aborted" instead of "Invalid file system", "No filesysten found", ...

Agree. We just need to fail gracefully with a reasonable message.
